main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('stones/', views.stones_index, name='index'),
  path('stones/<int:stone_id>/', views.stones_detail, name='detail'),
  path('stones/create/', views.StoneCreate.as_view(), name='stones_create'),
  path('stones/<int:pk>/update/', views.StoneUpdate.as_view(), name='stones_update'),
  path('stones/<int:pk>/delete/', views.StoneDelete.as_view(), name='stones_delete'),
  path('stones/<int:stone_id>/add_use/', views.add_use, name='add_use'),
  path('stones/<int:stone_id>/assoc_villain/<int:villain_id>/', views.assoc_villain, name='assoc_villain'),
  path('stones/<int:stone_id>/unassoc_villain/<int:villain_id>/', views.unassoc_villain, name='unassoc_villain'),
  path('villains/', views.VillainList.as_view(), name='villains_index'),
  path('villains/<int:pk>/', views.VillainDetail.as_view(), name='villains_detail'),
  path('villains/create/', views.VillainCreate.as_view(), name='villains_create'),
  path('villains/<int:pk>/update/', views.VillainUpdate.as_view(), name='villains_update'),
  path('villains/<int:pk>/delete/', views.VillainDelete.as_view(), name='villains_delete'),
]

thecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

REASONS = (
    ('P', 'Personal Gain'),
    ('A', 'Against Avengers'),
    ('S', 'Showing Off...Again')
)

# Create your models here.

class Villain(models.Model):
  name = models.CharField(max_length=50)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('villains_detail', kwargs={'pk': self.id})


class Stone(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    description = models.TextField(max_length=250)

    villains = models.ManyToManyField(Villain)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'stone_id': self.id})

class Use(models.Model):
  date = models.DateField('Date Used')
  reason = models.CharField(
    max_length=1,
        choices=REASONS,
        default=REASONS[0][0]
  )
  
  stone = models.ForeignKey(Stone, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_reason_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Use

class UseForm(ModelForm):
  class Meta:
    model = Use
    fields = ['date', 'reason']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Stone, Villain
from .forms import UseForm

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def stones_index(request):
    stones = Stone.objects.all()
    return render(request, 'stones/index.html', { 'stones': stones })

def stones_detail(request, stone_id):
  stone = Stone.objects.get(id=stone_id)
  id_list = stone.villains.all().values_list('id')
  villains_stone_doesnt_have = Villain.objects.exclude(id__in=id_list)
  use_form = UseForm()
  return render(request, 'stones/detail.html', { 
    'stone': stone,
    'use_form': use_form,
    'villains': villains_stone_doesnt_have
  })

class StoneCreate(CreateView):
  model = Stone
  fields = ['name', 'color', 'description']

class StoneUpdate(UpdateView):
  model = Stone
  fields = ['color', 'description']

class StoneDelete(DeleteView):
  model = Stone
  success_url = '/stones'
  
def add_use(request, stone_id):
  form = UseForm(request.POST)
  if form.is_valid():
    new_use= form.save(commit=False)
    new_use.stone_id = stone_id
    new_use.save()
  return redirect('detail', stone_id=stone_id)

class VillainList(ListView):
  model = Villain

class VillainDetail(DetailView):
  model = Villain

class VillainCreate(CreateView):
  model = Villain
  fields = '__all__'

class VillainUpdate(UpdateView):
  model = Villain
  fields = ['name']

class VillainDelete(DeleteView):
  model = Villain
  success_url = '/villains'

def assoc_villain(request, stone_id, villain_id):
  Stone.objects.get(id=stone_id).villains.add(villain_id)
  return redirect('detail', stone_id=stone_id)

def unassoc_villain(request, stone_id, villain_id):
  Stone.objects.get(id=stone_id).villains.remove(villain_id)
  return redirect('detail', stone_id=stone_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About The Collector</h1>
    <hr>
    <p>Beware of The Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>The Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;The Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'villains_create' %}">Add a Villain</a></li>
          <li><a href="{% url 'villains_index' %}">View All Villains</a></li>
          <li><a href="{% url 'stones_create' %}">Add Infinity Stone</a></li>
          <li><a href="{% url 'index' %}">View Infinity Stones</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; Marvel &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/stone_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Infinity Stone</h1>

  <h4>Are you sure you want to delete one of The Collector's most prized possessions, the <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' stone.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/stone_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Infinity Stone</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/villain_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Villain</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'villains_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/villain_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Villain Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ villain.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'villains_update' villain.id %}">Edit</a>
        <a href="{% url 'villains_delete' villain.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/villain_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Villain</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/villain_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Villain List</h1>

{% for villain in villain_list %}
  <a href="{% url 'villains_detail' villain.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ villain.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/stones/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Infinity Stones</h1>

  <div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
            <span class="card-title">{{ stone.name }}</span>
            <p>Color: {{ stone.color }}</p>
            <p>Description: {{ stone.description | linebreaks }}</p>
        </div>
        <div class="card-action">
            <a href="{% url 'stones_update' stone.id %}">Edit</a>
            <a href="{% url 'stones_delete' stone.id %}">Delete</a>
        </div>
    </div>
  </div>

  <div class="col s6">
    <form action="{% url 'add_use' stone.id %}" method="POST">
      {% csrf_token %}
      {{ use_form.as_p }}
      <input type="submit" class="btn" value="Add Reason">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Used</th></tr>
      </thead>
      <tbody>
        {% for use in stone.use_set.all %}
          <tr>
            <td>{{use.date}}</td>
            <td>{{use.get_reason_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>Other Villains who have possessed the {{ stone.name }}</h3>
    {% if stone.villains.count %}
      {% for villain in stone.villains.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ villain.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_villain' stone.id villain.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>None</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Have these Villains used the {{ stone.name }}?</h3>
    {% if villains.count %}
      {% for villain in villains.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ villain.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_villain' stone.id villain.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>The {{stone.name}} Has Been Used By All Available Villains</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_reason');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/stones/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Infinity Stones</h1>

{% for stone in stones %}
  <div class="card">
    <a href="{% url 'detail' stone.id %}">
        <div class="card-content">
        <span class="card-title">{{ stone.name }}</span>
        <p>Color: {{ stone.color }}</p>
        <p>Description: {{ stone.description | linebreaks }}</p>
        </div>
    </a>
  </div>
{% endfor %}

{% endblock %}